/*
 * GameHub game list.
 *
 * To add a game:
 * 1. Create a folder in games, for example games/my_game.
 * 2. Put the playable file at games/my_game/index.html.
 * 3. Add one entry below with at least the folder name.
 *
 * Optional fields: name, description, category, difficulty, icon, tags,
 * version, author, estimatedPlayTime, aiEffortRating, defaultRating,
 * input, rendering, saveSupport, libraryList.
 */
window.GAMEHUB_LIBRARY_SECTIONS = [
    {
        id: 'polished',
        label: 'Polished'
    },
    {
        id: 'ai-slope',
        label: 'AI Slope'
    }
];

window.GAMEHUB_GAMES = [
    {
        folder: 'snake',
        name: 'Snake!',
        description: 'Classic Snake game with AI opponents and multiple food types',
        category: 'Arcade',
        difficulty: 'Easy',
        icon: 'S',
        tags: ['2d', 'classic', 'arcade', 'ai'],
        author: 'GameHub Team',
        estimatedPlayTime: 10,
        aiEffortRating: 4,
        defaultRating: 3,
        libraryList: 'polished'
    },
    {
        folder: 'miniinvaders',
        name: 'Mini Invaders',
        description: 'Classic Space Invaders! Shoot descending aliens before they reach the bottom.',
        category: 'Arcade',
        difficulty: 'Medium',
        icon: 'MI',
        tags: ['2d', 'arcade', 'shooter', 'retro', 'classic'],
        author: 'GameHub Team',
        estimatedPlayTime: 15,
        aiEffortRating: 4,
        defaultRating: 5,
        libraryList: 'polished'
    },
    {
        folder: 'frontier_wayfarer',
        name: 'Frontier Wayfarer',
        description: 'Forge a career across seven connected galaxies through contracts, factions, trade, exploration, and inertial starfighter combat.',
        category: 'Action RPG',
        difficulty: 'Medium',
        icon: 'M2',
        tags: ['2d', 'open-world', 'space', 'starfighter', 'rpg', 'contracts', 'factions', 'galaxies'],
        version: '4.0.0',
        author: 'GameHub',
        estimatedPlayTime: 45,
        aiEffortRating: 5,
        defaultRating: 1,
        input: 'Keyboard + Mouse',
        rendering: 'Canvas',
        saveSupport: 'Campaign',
        libraryList: 'ai-slope'
    },
    {
        folder: 'Cellvive',
        name: 'Cellvive',
        description: 'Survive as a blob-like cell. Eat smaller cells to grow while avoiding bigger ones.',
        category: 'Action',
        difficulty: 'Easy',
        icon: 'CV',
        tags: ['2d', 'survival', 'action', 'arcade', 'cells'],
        author: 'GameHub Team',
        estimatedPlayTime: 10,
        aiEffortRating: 3,
        defaultRating: 2,
        libraryList: 'ai-slope'
    },
    {
        folder: 'cosmicdrifter',
        name: 'Cosmic Drifter',
        description: 'Drift through shattered worlds, collect resources, avoid hazards, and upgrade your ship.',
        category: 'Exploration',
        difficulty: 'Medium',
        icon: 'CD',
        tags: ['2d', 'exploration', 'survival', 'space', 'open-world', 'upgrades'],
        author: 'GameHub Team',
        estimatedPlayTime: 10,
        aiEffortRating: 2,
        defaultRating: 1,
        libraryList: 'ai-slope'
    },
    {
        folder: 'stickperson',
        name: 'Stickman Platformer',
        description: 'A simple 2D platformer with a stickman character',
        category: 'Platformer',
        difficulty: 'Easy',
        icon: 'SP',
        tags: ['2d', 'platformer', 'action'],
        author: 'GameHub Team',
        estimatedPlayTime: 10,
        aiEffortRating: 2,
        defaultRating: 1,
        libraryList: 'ai-slope'
    },
    {
        folder: 'elemental-stickman',
        name: 'Elemental Stickman',
        description: 'Gesture-cast four elements in a side-scrolling stickman platform fighting sandbox.',
        category: 'Platformer',
        difficulty: 'Medium',
        icon: 'ES',
        tags: ['2d', 'platformer', 'fighting', 'elemental', 'gesture', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 15,
        aiEffortRating: 3,
        defaultRating: 1,
        input: 'Keyboard + Mouse',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'stormline-runner',
        name: 'Stormline Runner',
        description: 'Endless neon-weather platformer where generated storm fronts reshape hazards, routes, and talent value.',
        category: 'Platformer',
        difficulty: 'Medium',
        icon: 'SR',
        tags: ['2d', 'platformer', 'arcade', 'endless', 'procedural', 'talents'],
        author: 'GameHub',
        estimatedPlayTime: 10,
        aiEffortRating: 3,
        defaultRating: 1,
        input: 'Keyboard',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'echo_maze',
        name: 'Echo Maze',
        description: 'Infinite fog-of-war maze run where you stabilize Echo Anchors and escape before the maze wakes fully.',
        category: 'Exploration',
        difficulty: 'Medium',
        icon: 'EM',
        tags: ['2d', 'exploration', 'maze', 'fog-of-war', 'procedural', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 20,
        aiEffortRating: 5,
        defaultRating: 4,
        input: 'Keyboard',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'polished'
    },
    {
        folder: 'lanternfall',
        name: 'Lanternfall',
        description: 'Chart an endless lantern-lit cave, gather glimmering finds, and push deeper through procedural darkness.',
        category: 'Exploration',
        difficulty: 'Easy',
        icon: 'LF',
        tags: ['2d', 'exploration', 'procedural', 'cave', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 12,
        aiEffortRating: 3,
        defaultRating: 2,
        input: 'Keyboard + Touch',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'blockdodge',
        name: 'Block Dodge',
        description: 'Control a square and dodge falling blocks as the difficulty increases.',
        category: 'Arcade',
        difficulty: 'Easy',
        icon: 'BD',
        tags: ['2d', 'arcade', 'reflex', 'survival'],
        author: 'GameHub Team',
        estimatedPlayTime: 5,
        aiEffortRating: 1,
        defaultRating: 3,
        libraryList: 'polished'
    },
    {
        folder: 'color_stream_reactor',
        name: 'Color Stream Reactor',
        description: 'Match neon energy colors before the falling stream overloads the reactor.',
        category: 'Arcade',
        difficulty: 'Medium',
        icon: 'CSR',
        tags: ['arcade', 'reflex', 'color-match', 'neon'],
        author: 'GameHub',
        estimatedPlayTime: 5,
        aiEffortRating: 2,
        defaultRating: 4,
        libraryList: 'polished'
    },
    {
        folder: 'gloomvault-extraction',
        name: 'Gloomvault Extraction',
        description: 'Isometric roguelite dungeon crawler with extraction mechanics and loot progression.',
        category: 'Action RPG',
        difficulty: 'Hard',
        icon: 'GE',
        tags: ['roguelite', 'action', 'loot', 'dungeon-crawler'],
        author: 'GameHub',
        estimatedPlayTime: 35,
        aiEffortRating: 5,
        defaultRating: 4,
        libraryList: 'polished'
    },
    {
        folder: 'never-south',
        name: 'Never South',
        description: 'Grid roguelite deckbuilder where every card moves you north, west, or east, but never south.',
        category: 'Strategy',
        difficulty: 'Medium',
        icon: 'NS',
        tags: ['2d', 'roguelite', 'deckbuilder', 'puzzle', 'grid', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 15,
        aiEffortRating: 3,
        defaultRating: 2,
        input: 'Keyboard + Mouse',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'contraband-skies',
        name: 'Contraband Skies',
        description: 'Run illegal sky-courier contracts through a living stormpunk atmosphere in a saved roguelite campaign.',
        category: 'Strategy',
        difficulty: 'Medium',
        icon: 'CS',
        tags: ['2d', 'strategy', 'roguelite', 'campaign', 'routes', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 15,
        aiEffortRating: 3,
        defaultRating: 1,
        input: 'Mouse + Keyboard',
        rendering: 'Canvas',
        saveSupport: 'Campaign',
        libraryList: 'ai-slope'
    },
    {
        folder: 'void_signal',
        name: 'Void Signal',
        category: 'Other',
        icon: 'VS',
        aiEffortRating: 1,
        defaultRating: 1,
        libraryList: 'ai-slope'
    },
    {
        folder: 'depthbound',
        name: 'Depthbound',
        description: 'Dive through an infinite gun dungeon of procedural rooms, talent branches, relics, curses, shops, elites, and boss gates.',
        category: 'Action RPG',
        difficulty: 'Hard',
        icon: 'DB',
        tags: ['2d', 'action', 'roguelite', 'dungeon-crawler', 'shooter', 'procedural'],
        author: 'GameHub',
        estimatedPlayTime: 20,
        aiEffortRating: 3,
        defaultRating: 2,
        input: 'Keyboard + Mouse',
        rendering: 'Canvas',
        saveSupport: 'High Score',
        libraryList: 'ai-slope'
    },
    {
        folder: 'reaction_diffusion_simulator',
        name: 'Reaction Diffusion Simulator',
        description: 'A hands-on Gray-Scott reaction-diffusion lab for painting, tuning, and studying generative patterns.',
        category: 'Simulation',
        difficulty: 'Medium',
        icon: 'RD',
        tags: ['simulation', 'science', 'sandbox', 'canvas', 'generative'],
        author: 'GameHub',
        estimatedPlayTime: 15,
        aiEffortRating: 3,
        defaultRating: 3,
        libraryList: 'polished'
    },
    {
        folder: 'the_gravity_locksmith',
        name: 'The Gravity Locksmith',
        description: 'Break into impossible sky-vaults by stealing the direction of falling. Flip gravity, dodge spikes, outrun the shadow.',
        category: 'Platformer',
        difficulty: 'Medium',
        icon: 'TGL',
        tags: ['2d', 'platformer', 'puzzle', 'gravity', 'action'],
        author: 'GameHub Team',
        estimatedPlayTime: 15,
        aiEffortRating: 4,
        defaultRating: 4,
        libraryList: 'polished'
    },
    {
        folder: 'castlefall_valley',
        name: 'Castlefall Valley',
        description: 'Command troops, build your keep, and lead a hero through a terraced side-scroller siege battlefield.',
        category: 'Strategy',
        difficulty: 'Medium',
        icon: 'CV',
        tags: ['2d', 'strategy', 'siege', 'side-scroller', 'canvas'],
        author: 'GameHub',
        estimatedPlayTime: 15,
        aiEffortRating: 3,
        defaultRating: 1,
        input: 'Keyboard + Touch',
        rendering: 'Canvas',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'skySquirrel',
        name: 'Sky Squirrel',
        description: 'Launch from a mountain summit and carve a wingsuit line across a procedural island in native WebGL.',
        category: 'Simulation',
        difficulty: 'Medium',
        icon: 'SS',
        tags: ['3d', 'wingsuit', 'flight', 'island', 'webgl', 'procedural'],
        author: 'GameHub',
        estimatedPlayTime: 12,
        aiEffortRating: 4,
        defaultRating: 1,
        input: 'Keyboard + Mouse',
        rendering: 'Native WebGL',
        saveSupport: 'None',
        libraryList: 'ai-slope'
    },
    {
        folder: 'lumenkin',
        name: 'Lumenkin',
        description: 'Guide an autonomous bioluminescent lineage through five fast, decision-rich management eras and carry a living civilization through the Great Bloom.',
        category: 'Simulation',
        difficulty: 'Medium',
        icon: 'LK',
        tags: ['2d', 'pixel-art', 'simulation', 'evolution', 'colony', 'strategy', 'campaign'],
        author: 'GameHub',
        estimatedPlayTime: 90,
        aiEffortRating: 5,
        defaultRating: 1,
        input: 'Mouse + Keyboard',
        rendering: 'Canvas',
        saveSupport: 'Campaign',
        libraryList: 'ai-slope'
    }
];
