(function (ns) {
    const C = (aetherium, sunshards, helionite) => ({ aetherium: aetherium || 0, sunshards: sunshards || 0, helionite: helionite || 0 });
    const HULLS = {
        wayfarer: { id: 'wayfarer', name: 'Wayfarer', maker: 'Frontier Guilds', description: 'A balanced free-pilot frame built to accept almost any frontier fitting.', faction: 'independents', hull: 140, massLimit: 52, cargo: 0, reactor: 0, thrust: 1, strafe: 1, maxSpeed: 340, shield: 1, cooling: 0, sensor: 0, radius: 17, cost: C(0), unlock: 'starter', shape: [[0,-31],[8,-18],[13,-8],[28,13],[20,20],[8,14],[0,22],[-8,14],[-20,20],[-28,13],[-13,-8],[-8,-18]] },
        guild_mule: { id: 'guild_mule', name: 'Guild Mule', maker: 'Frontier Guilds', description: 'A broad-haul workhorse with deep holds and forgiving structural reserves.', faction: 'independents', hull: 195, massLimit: 68, cargo: 14, reactor: 4, thrust: .78, strafe: .72, maxSpeed: 270, shield: 1, cooling: 1, sensor: 0, radius: 22, cost: C(1100, 4, 8), unlock: 'trade2', majorOnly: true, shape: [[0,-25],[14,-18],[25,-4],[27,19],[13,27],[0,22],[-13,27],[-27,19],[-25,-4],[-14,-18]] },
        concord_kestrel: { id: 'concord_kestrel', name: 'Concord Kestrel', maker: 'Helion Concord', description: 'A narrow patrol interceptor tuned for acceleration, lateral authority, and pursuit.', faction: 'concord', hull: 105, massLimit: 45, cargo: -4, reactor: 0, thrust: 1.28, strafe: 1.25, maxSpeed: 420, shield: 1.08, cooling: 2, sensor: 80, radius: 14, cost: C(1350, 0, 18), unlock: 'concord10', majorOnly: true, shape: [[0,-38],[7,-18],[24,7],[12,12],[8,27],[0,18],[-8,27],[-12,12],[-24,7],[-7,-18]] },
        concord_bulwark: { id: 'concord_bulwark', name: 'Concord Bulwark', maker: 'Helion Concord', description: 'An armored line gunship that trades speed and cooling for mass and shield stability.', faction: 'concord', hull: 235, massLimit: 76, cargo: 2, reactor: 8, thrust: .72, strafe: .68, maxSpeed: 255, shield: 1.3, cooling: -3, sensor: -60, radius: 25, cost: C(2100, 0, 42), unlock: 'bulwark', majorOnly: true, shape: [[0,-29],[15,-22],[30,-6],[31,17],[17,28],[7,22],[0,28],[-7,22],[-17,28],[-31,17],[-30,-6],[-15,-22]] },
        corsair_wraith: { id: 'corsair_wraith', name: 'Corsair Wraith', maker: 'Null Corsairs', description: 'A heat-shedding ambush frame made for speed, sensors, and dangerous light fittings.', faction: 'corsairs', hull: 92, massLimit: 43, cargo: -5, reactor: -4, thrust: 1.2, strafe: 1.18, maxSpeed: 405, shield: .85, cooling: 7, sensor: 220, radius: 15, cost: C(1250, 12, 12), unlock: 'corsairs10', majorOnly: true, shape: [[0,-34],[9,-20],[29,-8],[17,2],[28,22],[7,16],[0,25],[-7,16],[-28,22],[-17,2],[-29,-8],[-9,-20]] },
        meridian_ranger: { id: 'meridian_ranger', name: 'Meridian Ranger', maker: 'Frontier Guilds', description: 'A long-range survey frame with generous power, cooling, cargo, and sensor authority.', faction: 'independents', hull: 150, massLimit: 58, cargo: 6, reactor: 14, energyRecharge: 2, thrust: .96, strafe: 1.16, turn: 1.08, maxSpeed: 350, shield: 1.05, cooling: 6, sensor: 380, radius: 18, cost: C(1900, 28, 16), unlock: 'ranger', vendors: ['shatterline_post', 'rim_observatory'], mounts: { forward: 30, lateral: 12 }, shape: [[0,-36],[10,-24],[16,-7],[31,9],[25,22],[10,17],[0,29],[-10,17],[-25,22],[-31,9],[-16,-7],[-10,-24]] },
        concord_lancer: { id: 'concord_lancer', name: 'Concord Lancer', maker: 'Helion Concord', description: 'A long-nosed artillery platform that converts cargo and lateral agility into pursuit firepower.', faction: 'concord', hull: 125, massLimit: 60, cargo: -6, reactor: 10, energyRecharge: 1, thrust: 1.16, strafe: .84, turn: .93, maxSpeed: 385, shield: 1.15, cooling: -2, sensor: 120, radius: 18, cost: C(2300, 8, 48), unlock: 'concordElite', majorOnly: true, mounts: { forward: 42, lateral: 10 }, shape: [[0,-46],[7,-28],[14,-14],[34,9],[18,15],[10,32],[0,24],[-10,32],[-18,15],[-34,9],[-14,-14],[-7,-28]] },
        corsair_ravager: { id: 'corsair_ravager', name: 'Corsair Ravager', maker: 'Null Corsairs', description: 'A brutal close-range attack hull built to vent heat while carrying heavyweight weapons.', faction: 'corsairs', hull: 180, massLimit: 65, cargo: -3, reactor: 0, thrust: 1.08, strafe: .92, turn: .96, maxSpeed: 355, shield: .8, cooling: 12, sensor: 20, radius: 21, cost: C(2200, 15, 45), unlock: 'corsairElite', majorOnly: true, mounts: { forward: 24, lateral: 20 }, shape: [[0,-31],[13,-25],[22,-10],[37,-2],[24,9],[33,29],[9,20],[0,30],[-9,20],[-33,29],[-24,9],[-37,-2],[-22,-10],[-13,-25]] },
        prism_eidolon: { id: 'prism_eidolon', name: 'Prism Eidolon', maker: 'Rim Observatory', description: 'An anomaly-tuned energy craft with extraordinary shields, reactor depth, and lateral control.', faction: 'independents', hull: 110, massLimit: 55, cargo: -8, reactor: 28, energyRecharge: 4, thrust: .98, strafe: 1.28, turn: 1.18, maxSpeed: 370, shield: 1.4, cooling: 4, sensor: 260, radius: 20, cost: C(2600, 50, 36), unlock: 'capitalVeteran', vendors: ['rim_observatory'], mounts: { forward: 34, lateral: 17 }, shape: [[0,-41],[9,-25],[28,-17],[19,-2],[38,15],[16,13],[9,31],[0,23],[-9,31],[-16,13],[-38,15],[-19,-2],[-28,-17],[-9,-25]] }
    };

    const WEAPON_TYPES = {
        pulse: { type: 'bolt', color: '#55f0ad', speed: 720, life: 1.5 },
        rail: { type: 'rail', color: '#ce75ff', speed: 1080, life: 1.2, pierce: 1 },
        seeker: { type: 'missile', color: '#ffbd59', speed: 387, life: 2.24, turnRate: 2.4, splash: 70 },
        beam: { type: 'beam', color: '#55d7ff', speed: 1450, life: .45, charge: { min: .35, max: 1.8 } },
        scatter: { type: 'scatter', color: '#ff4f91', speed: 640, life: .75, pellets: 5, spread: .22 },
        arc: { type: 'arc', color: '#55f0d2', speed: 780, life: 1, chain: 2, chainRange: 180 },
        solar: { type: 'solar', color: '#ff673d', speed: 880, life: 1.1, ramp: { step: .12, max: 1.75, reset: .45 } },
        bloodhound: { type: 'missile', color: '#ff315c', speed: 324, life: 3.08, turnRate: 2.8, splash: 125, lock: .8 },
        nova: { type: 'nova', color: '#b96cff', speed: 720, life: 1.6, pierce: 2, splash: 95, charge: { min: .45, max: 2.2, stages: 3 } },
        ion: { type: 'ion', color: '#54a7ff', speed: 940, life: 1.2, status: { disabled: 1.35, slow: .45 } },
        flak: { type: 'flak', color: '#ff9b42', speed: 620, life: .7, pellets: 4, spread: .16, proximity: 58, antiProjectile: true, splash: 42 },
        mine: { type: 'mine', color: '#e8b15f', speed: 260, life: 3.6, proximity: 72, splash: 92 },
        vortex: { type: 'vortex', color: '#d8f7ff', speed: 560, life: 1.55, pierce: 1, splash: 115, siphon: { energy: 10, heat: 8 }, vortex: { radius: 190, pull: 85 } }
    };
    Object.assign(HULLS, {
        aster_cartograph: { id: 'aster_cartograph', name: 'Aster Cartograph', maker: 'Aster Collective', description: 'A survey cathedral in miniature, built for sensors, precision energy, and distant map work.', faction: 'aster_collective', hull: 155, massLimit: 72, cargo: 4, reactor: 30, energyRecharge: 5, thrust: 1.02, strafe: 1.18, turn: 1.14, maxSpeed: 380, shield: 1.18, cooling: 8, sensor: 620, radius: 19, cost: C(3600, 95, 54), unlock: 'asterLate', vendors: ['aster_archive'], mounts: { forward: 36, lateral: 18 }, shape: [[0,-48],[11,-30],[22,-12],[40,4],[26,16],[17,35],[0,28],[-17,35],[-26,16],[-40,4],[-22,-12],[-11,-30]] },
        orchid_riftneedle: { id: 'orchid_riftneedle', name: 'Orchid Riftneedle', maker: 'Orchid Synod', description: 'A ritual phase-skimmer that wins by angle, heat control, and impossible exit vectors.', faction: 'orchid_synod', hull: 118, massLimit: 60, cargo: -10, reactor: 24, energyRecharge: 6, thrust: 1.24, strafe: 1.42, turn: 1.35, maxSpeed: 430, shield: 1.02, cooling: 15, sensor: 340, radius: 16, cost: C(3300, 125, 50), unlock: 'orchidLate', vendors: ['orchid_spindle'], mounts: { forward: 44, lateral: 12 }, shape: [[0,-54],[6,-33],[18,-21],[9,-6],[37,13],[12,10],[6,38],[0,27],[-6,38],[-12,10],[-37,13],[-9,-6],[-18,-21],[-6,-33]] },
        auric_vaultbarge: { id: 'auric_vaultbarge', name: 'Auric Vaultbarge', maker: 'Auric Combine', description: 'A fortified merchant-prince hull with deep holds, heavy mount budget, and poor evasive manners.', faction: 'auric_combine', hull: 260, massLimit: 92, cargo: 28, reactor: 16, energyRecharge: 1, thrust: .72, strafe: .62, turn: .82, maxSpeed: 255, shield: 1.22, cooling: 0, sensor: -80, radius: 27, cost: C(4200, 55, 90), unlock: 'auricLate', vendors: ['auric_exchange'], mounts: { forward: 28, lateral: 25 }, shape: [[0,-35],[19,-30],[34,-12],[38,19],[21,34],[8,27],[0,35],[-8,27],[-21,34],[-38,19],[-34,-12],[-19,-30]] },
        cyan_salvage_lantern: { id: 'cyan_salvage_lantern', name: 'Cyan Salvage Lantern', maker: 'Cyan Nomads', description: 'A nomad recovery frame with tractor authority, shield uptime, and cargo room for strange finds.', faction: 'cyan_nomads', hull: 175, massLimit: 78, cargo: 12, reactor: 18, energyRecharge: 4, thrust: 1, strafe: 1.12, turn: 1.12, maxSpeed: 365, shield: 1.24, cooling: 6, sensor: 520, radius: 20, cost: C(3900, 80, 70), unlock: 'cyanLate', vendors: ['cyan_freeport'], mounts: { forward: 32, lateral: 20 }, shape: [[0,-40],[13,-25],[31,-18],[21,-2],[37,20],[15,17],[6,36],[0,24],[-6,36],[-15,17],[-37,20],[-21,-2],[-31,-18],[-13,-25]] },
        gemini_echelon_spear: { id: 'gemini_echelon_spear', name: 'Gemini Echelon Spear', maker: 'Gemini Directorate', description: 'A paired-command strike frame that favors lock discipline, range control, and doctrinal aggression.', faction: 'gemini_directorate', hull: 150, massLimit: 74, cargo: -8, reactor: 22, energyRecharge: 3, thrust: 1.18, strafe: 1.04, turn: 1.08, maxSpeed: 410, shield: 1.14, cooling: 4, sensor: 260, radius: 18, cost: C(4050, 70, 105), unlock: 'geminiLate', vendors: ['gemini_crown'], mounts: { forward: 50, lateral: 13 }, shape: [[0,-58],[8,-36],[16,-17],[42,7],[19,13],[12,36],[0,28],[-12,36],[-19,13],[-42,7],[-16,-17],[-8,-36]] },
        concord_solar_bulwark: { id: 'concord_solar_bulwark', name: 'Concord Solar Bulwark', maker: 'Helion Concord', description: 'A late-line shield fortress for captains who would rather hold a lane than dodge it.', faction: 'concord', hull: 310, massLimit: 96, cargo: 4, reactor: 28, energyRecharge: 1, thrust: .68, strafe: .64, turn: .76, maxSpeed: 245, shield: 1.55, cooling: -2, sensor: 40, radius: 29, cost: C(4800, 40, 125), unlock: 'concordCapital', vendors: ['helion_bastion', 'sunfall_citadel', 'marchlight_citadel'], mounts: { forward: 30, lateral: 28 }, shape: [[0,-38],[20,-31],[39,-10],[43,17],[24,37],[8,29],[0,39],[-8,29],[-24,37],[-43,17],[-39,-10],[-20,-31]] },
        frontier_horizon_ark: { id: 'frontier_horizon_ark', name: 'Frontier Horizon Ark', maker: 'Frontier Guilds', description: 'A tier-seven free-pilot flagship for captains who have made the whole gate map feel small.', faction: 'independents', hull: 240, massLimit: 110, cargo: 20, reactor: 36, energyRecharge: 5, thrust: .94, strafe: 1.02, turn: 1.02, maxSpeed: 340, shield: 1.35, cooling: 10, sensor: 760, radius: 26, cost: C(6200, 160, 140), unlock: 'allGalaxies', vendors: ['waypoint_zero', 'shatterline_post', 'terminus_exchange'], mounts: { forward: 42, lateral: 24 }, shape: [[0,-52],[16,-36],[31,-16],[49,6],[35,23],[18,39],[0,34],[-18,39],[-35,23],[-49,6],[-31,-16],[-16,-36]] },
        null_crown_reaver: { id: 'null_crown_reaver', name: 'Null Crown Reaver', maker: 'Null Corsairs', description: 'A tier-seven raider crown: overgunned, overvented, and too proud to carry anything honest.', faction: 'corsairs', hull: 190, massLimit: 96, cargo: -12, reactor: 12, energyRecharge: 7, thrust: 1.22, strafe: 1.18, turn: 1.15, maxSpeed: 425, shield: .92, cooling: 20, sensor: 300, radius: 22, cost: C(5600, 95, 165), unlock: 'nullCrown', vendors: ['rust_orbit', 'crown_anchorage', 'nullwake_hold', 'deadstar_anchorage'], mounts: { forward: 36, lateral: 28 }, shape: [[0,-43],[17,-33],[29,-14],[53,-5],[30,10],[44,34],[12,22],[0,38],[-12,22],[-44,34],[-30,10],[-53,-5],[-29,-14],[-17,-33]] }
    });
    Object.assign(ns.Data.MODULES, {
        beam_lance: { id: 'beam_lance', name: 'Concord Beam Lance', description: 'Hold fire to charge a cyan lance, then release or reach full charge.', slot: 'primary', mass: 10, energy: 22, heat: 28, damage: 62, fireRate: .9, weapon: 'beam', cost: C(620, 4, 34), tier: 3, unlock: 'concord10' },
        scatter_array: { id: 'scatter_array', name: 'Corsair Scatter Array', description: 'A violent magenta spread built for close attack runs.', slot: 'primary', mass: 7, energy: 13, heat: 21, damage: 11, fireRate: .42, weapon: 'scatter', cost: C(480, 8, 18), tier: 2, unlock: 'corsairs10' },
        arc_projector: { id: 'arc_projector', name: 'Guild Arc Projector', description: 'A teal discharge that jumps between tightly clustered targets.', slot: 'primary', mass: 8, energy: 17, heat: 18, damage: 31, fireRate: .7, weapon: 'arc', cost: C(520, 16, 8), tier: 3, unlock: 'trade2' },
        solar_repeater: { id: 'solar_repeater', name: 'Solar Repeater', description: 'Red-orange pulse fire grows stronger and hotter while the trigger stays down.', slot: 'primary', mass: 9, energy: 9, heat: 9, damage: 19, fireRate: .16, weapon: 'solar', cost: C(780, 4, 42), tier: 4, unlock: 'capital', vendors: ['helion_bastion', 'sunfall_citadel'] },
        bloodhound_rack: { id: 'bloodhound_rack', name: 'Bloodhound Torpedo Rack', description: 'Hold target lock before launching a slow crimson torpedo with a punishing blast radius.', slot: 'primary', mass: 13, energy: 28, heat: 32, damage: 130, fireRate: 2.7, weapon: 'bloodhound', cost: C(920, 10, 58), tier: 4, unlock: 'capital', vendors: ['rust_orbit', 'deadstar_anchorage'] },
        prism_nova_coil: { id: 'prism_nova_coil', name: 'Prism Nova Coil', description: 'A three-stage violet charge releases a piercing detonation at maximum resonance.', slot: 'primary', mass: 12, energy: 24, heat: 30, damage: 72, fireRate: 1.15, weapon: 'nova', cost: C(960, 42, 28), tier: 4, unlock: 'capitalVeteran', vendors: ['rim_observatory'] },
        ion_needler: { id: 'ion_needler', name: 'Ion Needler', description: 'Blue needles suppress hostile drives and weapons instead of maximizing hull damage.', slot: 'primary', mass: 8, energy: 10, heat: 11, damage: 14, fireRate: .24, weapon: 'ion', cost: C(700, 22, 24), tier: 3, unlock: 'rim', vendors: ['rim_observatory', 'vanguard_gate'] },
        flak_array: { id: 'flak_array', name: 'Flak Array', description: 'Orange proximity bursts shred small craft and intercept hostile missiles.', slot: 'primary', mass: 10, energy: 16, heat: 20, damage: 18, fireRate: .62, weapon: 'flak', cost: C(760, 6, 38), tier: 3, unlock: 'combat', vendors: ['shatterline_post', 'cinder_foundry'] },
        helion_capacitor: { id: 'helion_capacitor', name: 'Helion Capacitor Core', description: 'Massive reserve capacity for shields and charged weapons, with deliberately slow recovery.', slot: 'reactor', mass: 13, reactor: 145, energyRecharge: 15, cost: C(1050, 8, 44), tier: 4, unlock: 'capital', vendors: ['helion_bastion', 'sunfall_citadel'] },
        corsair_surge: { id: 'corsair_surge', name: 'Corsair Surge Core', description: 'Violent thirty-per-second recovery trades reserve depth for increased weapon heat.', slot: 'reactor', mass: 9, reactor: 105, energyRecharge: 30, weaponHeat: .15, cost: C(980, 6, 46), tier: 4, unlock: 'capital', vendors: ['rust_orbit', 'deadstar_anchorage'] },
        prism_resonance: { id: 'prism_resonance', name: 'Prism Resonance Core', description: 'An anomaly core blending strong recovery, cooling, and efficient active systems.', slot: 'reactor', mass: 11, reactor: 125, energyRecharge: 21, cooling: 8, abilityEnergyCost: -.15, cost: C(1100, 48, 28), tier: 4, unlock: 'capitalVeteran', vendors: ['rim_observatory'] },
        comet_drive: { id: 'comet_drive', name: 'Comet Drive', description: 'Extreme forward acceleration and speed with weak lateral and Light Speed steering authority.', slot: 'engine', mass: 12, thrust: 365, maxSpeed: 70, strafe: .82, turn: 2.2, braking: .95, lightSpeed: true, lightTurn: .72, lightCharge: .9, lightDeceleration: 1, cost: C(1080, 12, 42), tier: 4, unlock: 'capital', vendors: ['helion_bastion', 'sunfall_citadel'] },
        vector_dancer: { id: 'vector_dancer', name: 'Vector Dancer', description: 'High-authority maneuvering drive with exceptional strafe, turn, and braking response.', slot: 'engine', mass: 10, thrust: 315, maxSpeed: -20, strafe: 1.35, turn: 3.4, braking: 1.65, lightSpeed: true, lightTurn: 1.35, lightCharge: 1, lightDeceleration: .8, cost: C(1020, 28, 30), tier: 4, unlock: 'capital', vendors: ['shatterline_post', 'rim_observatory'] },
        siege_drive: { id: 'siege_drive', name: 'Siege Drive', description: 'A stable heavy-frame drive with rapid braking and reinforced collision compensation.', slot: 'engine', mass: 15, thrust: 285, maxSpeed: -55, strafe: .9, turn: 2.55, braking: 1.8, collisionResistance: .45, heavyStability: .25, lightSpeed: true, lightTurn: .9, lightCharge: 1.12, lightDeceleration: .7, cost: C(1140, 4, 55), tier: 4, unlock: 'capital', vendors: ['vanguard_gate', 'cinder_foundry'] },
        bastion_barrier: { id: 'bastion_barrier', name: 'Bastion Barrier', description: 'Overwhelming shield capacity that takes seven exposed seconds to begin recovering.', slot: 'defense', mass: 16, shield: 240, shieldRecharge: 3, shieldDelay: 7, cost: C(1120, 5, 60), tier: 4, unlock: 'capital', vendors: ['helion_bastion', 'sunfall_citadel'] },
        flux_screen: { id: 'flux_screen', name: 'Flux Screen', description: 'A moderate screen that returns almost immediately and regenerates at extraordinary speed.', slot: 'defense', mass: 11, shield: 110, shieldRecharge: 23, shieldDelay: 1, cost: C(1060, 36, 30), tier: 4, unlock: 'capitalVeteran', vendors: ['rim_observatory'] },
        reactive_plating: { id: 'reactive_plating', name: 'Reactive Plating', description: 'Shieldless armored plating adds ninety hull and reduces direct hull damage by twenty-five percent.', slot: 'defense', mass: 18, shield: 0, hullBonus: 90, armor: .25, shieldRecharge: 0, shieldDelay: 0, cost: C(1000, 0, 62), tier: 4, unlock: 'capital', vendors: ['rust_orbit', 'cinder_foundry'] },
        pulse_mk3: { id: 'pulse_mk3', name: 'Pulse Cannon III', description: 'A late Guild pulse assembly with hard cycling and civilized heat behavior.', slot: 'primary', mass: 9, energy: 15, heat: 15, damage: 34, fireRate: .14, weapon: 'pulse', cost: C(1150, 12, 62), tier: 5, unlock: 'capital', vendors: ['waypoint_zero', 'terminus_exchange'] },
        shard_minecaster: { id: 'shard_minecaster', name: 'Shard Minecaster', description: 'Lobs proximity shards that punish pursuit and crowd narrow combat lanes.', slot: 'primary', mass: 11, energy: 18, heat: 24, damage: 42, fireRate: 1.05, weapon: 'mine', cost: C(1300, 32, 74), tier: 5, unlock: 'orchidLate', vendors: ['orchid_spindle', 'rust_orbit'] },
        aurora_arc_web: { id: 'aurora_arc_web', name: 'Aurora Arc Web', description: 'A high-tier arc projector with longer chain reach for convoy and patrol fights.', slot: 'primary', mass: 10, energy: 21, heat: 22, damage: 39, fireRate: .58, weapon: 'arc', cost: C(1420, 48, 58), tier: 5, unlock: 'asterLate', vendors: ['aster_archive', 'cyan_freeport'] },
        sunlance: { id: 'sunlance', name: 'Sunlance', description: 'A Concord charge lance that favors one clean opening over noisy exchanges.', slot: 'primary', mass: 14, energy: 30, heat: 35, damage: 88, fireRate: 1.05, weapon: 'beam', cost: C(1600, 18, 96), tier: 6, unlock: 'concordCapital', vendors: ['sunfall_citadel', 'marchlight_citadel'] },
        gemini_lockstep_torpedoes: { id: 'gemini_lockstep_torpedoes', name: 'Gemini Lockstep Torpedoes', description: 'Paired doctrine torpedoes that demand a target lock and answer with heavy blast force.', slot: 'primary', mass: 15, energy: 31, heat: 34, damage: 152, fireRate: 2.5, weapon: 'bloodhound', cost: C(1550, 30, 112), tier: 6, unlock: 'geminiLate', vendors: ['gemini_crown'] },
        prism_crown_nova: { id: 'prism_crown_nova', name: 'Prism Crown Nova', description: 'A capital-veteran nova coil tuned for piercing resonance and violent detonation.', slot: 'primary', mass: 15, energy: 31, heat: 36, damage: 92, fireRate: 1.05, weapon: 'nova', cost: C(1720, 90, 88), tier: 6, unlock: 'capitalVeteran', vendors: ['rim_observatory', 'prism_wilds_station'] },
        horizon_singularity_lance: { id: 'horizon_singularity_lance', name: 'Horizon Singularity Lance', description: 'A tier-seven lance that tears mass inward and feeds energy back through the frame.', slot: 'primary', mass: 18, energy: 38, heat: 42, damage: 115, fireRate: 1.4, weapon: 'vortex', cost: C(2400, 140, 135), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'] },
        solar_crown_lance: { id: 'solar_crown_lance', name: 'Solar Crown Lance', description: 'A tier-seven Concord beam that rewards patient charge timing with overwhelming line pressure.', slot: 'primary', mass: 17, energy: 36, heat: 40, damage: 118, fireRate: .95, weapon: 'beam', cost: C(2300, 40, 165), tier: 7, unlock: 'concordCapital', vendors: ['sunfall_citadel', 'marchlight_citadel', 'dawnwall_bastion'] },
        null_crown_scatter: { id: 'null_crown_scatter', name: 'Null Crown Scatter', description: 'A tier-seven Corsair spread array for close captains with enough cooling to stay reckless.', slot: 'primary', mass: 16, energy: 24, heat: 34, damage: 20, fireRate: .34, weapon: 'scatter', cost: C(2180, 78, 155), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'] },
        aster_vortex_cartograph: { id: 'aster_vortex_cartograph', name: 'Aster Vortex Cartograph', description: 'A survey-combat singularity projector that gathers threats before the final detonation.', slot: 'primary', mass: 16, energy: 34, heat: 37, damage: 102, fireRate: 1.25, weapon: 'vortex', cost: C(2050, 135, 105), tier: 6, unlock: 'asterLate', vendors: ['aster_archive'] },
        aster_flux_core: { id: 'aster_flux_core', name: 'Aster Flux Core', description: 'A tier-five survey reactor with strong reserves, charting efficiency, and calm thermal behavior.', slot: 'reactor', mass: 12, reactor: 140, energyRecharge: 24, cooling: 5, abilityEnergyCost: -.08, cost: C(1450, 84, 48), tier: 5, unlock: 'asterLate', vendors: ['aster_archive', 'rim_observatory'] },
        auric_vault_core: { id: 'auric_vault_core', name: 'Auric Vault Core', description: 'A tier-six commercial reactor with massive reserves and slow, stable recovery for heavy hulls.', slot: 'reactor', mass: 15, reactor: 178, energyRecharge: 18, cost: C(1720, 42, 116), tier: 6, unlock: 'auricLate', vendors: ['auric_exchange'] },
        horizon_ark_core: { id: 'horizon_ark_core', name: 'Horizon Ark Core', description: 'A tier-seven frontier reactor for all-galaxy routes, charged weapons, and active systems.', slot: 'reactor', mass: 16, reactor: 198, energyRecharge: 28, cooling: 6, abilityEnergyCost: -.1, cost: C(2600, 150, 145), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'] },
        null_crown_core: { id: 'null_crown_core', name: 'Null Crown Surge Core', description: 'A tier-seven raider core with violent recovery, weapon heat risk, and generous overdrive headroom.', slot: 'reactor', mass: 13, reactor: 155, energyRecharge: 36, weaponHeat: .2, cost: C(2350, 90, 175), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'] },
        slipstream_drive: { id: 'slipstream_drive', name: 'Slipstream Drive', description: 'A tier-five exploration engine with smooth Light Speed handling and strong map-travel response.', slot: 'engine', mass: 12, thrust: 340, maxSpeed: 35, strafe: 1.12, turn: 3, braking: 1.25, lightTurn: 1.22, lightCharge: .88, lightDeceleration: .8, cost: C(1380, 58, 52), tier: 5, unlock: 'capitalVeteran', vendors: ['rim_observatory', 'terminus_exchange'] },
        sunfire_drive: { id: 'sunfire_drive', name: 'Sunfire Drive', description: 'A tier-six Concord line drive with fortress stability and deliberate Light Speed steering.', slot: 'engine', mass: 16, thrust: 315, maxSpeed: -10, strafe: .95, turn: 2.75, braking: 1.55, collisionResistance: .25, heavyStability: .18, lightTurn: .96, lightCharge: .82, lightDeceleration: .65, cost: C(1780, 34, 118), tier: 6, unlock: 'concordCapital', vendors: ['sunfall_citadel', 'marchlight_citadel'] },
        horizon_fold_drive: { id: 'horizon_fold_drive', name: 'Horizon Fold Drive', description: 'A tier-seven route engine built for long-distance captains who need speed without losing control.', slot: 'engine', mass: 15, thrust: 380, maxSpeed: 60, strafe: 1.14, turn: 3.2, braking: 1.4, lightTurn: 1.32, lightCharge: .72, lightDeceleration: .7, cost: C(2700, 155, 135), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'] },
        crown_ripper_drive: { id: 'crown_ripper_drive', name: 'Crown Ripper Drive', description: 'A tier-seven Corsair engine: fast, overvented, and built for violent attack angles.', slot: 'engine', mass: 14, thrust: 390, maxSpeed: 75, strafe: 1.18, turn: 3.35, braking: 1.1, lightTurn: 1.08, lightCharge: .8, lightDeceleration: .95, cost: C(2450, 90, 172), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'] },
        cargo_mk3: { id: 'cargo_mk3', name: 'Cargo Lattice III', description: 'A reinforced internal lattice for serious contract and trade careers.', slot: 'cargo', mass: 11, cargo: 38, cost: C(900, 12, 10), tier: 3, unlock: 'rim', vendors: ['shatterline_post', 'terminus_exchange'] },
        auric_vault_holds: { id: 'auric_vault_holds', name: 'Auric Vault Holds', description: 'Armored profit cells that add major cargo space without trusting the pilot.', slot: 'cargo', mass: 15, cargo: 54, armor: .06, cost: C(1500, 20, 42), tier: 5, unlock: 'auricLate', vendors: ['auric_exchange'] },
        cyan_tow_rig: { id: 'cyan_tow_rig', name: 'Cyan Tow Rig', description: 'Nomad tow architecture blends hold space with stronger recovery links.', slot: 'cargo', mass: 13, cargo: 42, interactionRange: 120, sensor: 160, cost: C(1380, 44, 28), tier: 5, unlock: 'cyanLate', vendors: ['cyan_freeport'] },
        horizon_deep_hold: { id: 'horizon_deep_hold', name: 'Horizon Deep Hold', description: 'A tier-seven frontier hold for long routes, relic work, and all-galaxy logistics.', slot: 'cargo', mass: 18, cargo: 72, sensor: 220, cost: C(2300, 110, 80), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'] },
        warden_screen: { id: 'warden_screen', name: 'Warden Screen', description: 'A disciplined midline defense screen with strong capacity and reliable recovery.', slot: 'defense', mass: 12, shield: 135, shieldRecharge: 10, shieldDelay: 3.8, cost: C(820, 8, 46), tier: 3, unlock: 'combat', vendors: ['helion_bastion', 'vanguard_gate'] },
        orchid_phase_membrane: { id: 'orchid_phase_membrane', name: 'Orchid Phase Membrane', description: 'A thin rift membrane with rapid recovery and a little damage slipping resistance.', slot: 'defense', mass: 10, shield: 125, shieldRecharge: 24, shieldDelay: .75, armor: .08, cost: C(1250, 72, 38), tier: 5, unlock: 'orchidLate', vendors: ['orchid_spindle'] },
        gemini_interdictor_screen: { id: 'gemini_interdictor_screen', name: 'Gemini Interdictor Screen', description: 'A doctrine-grade screen that favors capacity, stability, and hostile drive suppression.', slot: 'defense', mass: 15, shield: 205, shieldRecharge: 9, shieldDelay: 4.5, heavyStability: .12, cost: C(1680, 42, 100), tier: 6, unlock: 'geminiLate', vendors: ['gemini_crown'] },
        vector_afterburner_ii: { id: 'vector_afterburner_ii', name: 'Vector Afterburner II', description: 'A Light Speed-era vector surge with a longer burn and stronger pursuit acceleration.', slot: 'ability', mass: 5, cost: C(760, 18, 24), tier: 3, unlock: 'lightDrive', vendors: ['shatterline_post', 'vanguard_gate'], ability: { type: 'afterburner', cooldown: 5.6, duration: 2.5, energy: 24, thrustScale: 2.35, speedScale: 1.95 } },
        vector_afterburner_iii: { id: 'vector_afterburner_iii', name: 'Vector Afterburner III', description: 'A capital-grade sustained surge for heavy frames that need one decisive escape vector.', slot: 'ability', mass: 7, cost: C(1450, 55, 80), tier: 5, unlock: 'capitalVeteran', vendors: ['waypoint_zero', 'terminus_exchange'], ability: { type: 'afterburner', cooldown: 5.2, duration: 3.35, energy: 30, thrustScale: 2.55, speedScale: 2.08 } },
        horizon_vector_afterburner: { id: 'horizon_vector_afterburner', name: 'Horizon Vector Afterburner', description: 'A tier-seven frontier overdrive that holds a long burn without giving up pursuit speed.', slot: 'ability', mass: 8, cost: C(2380, 145, 130), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'], ability: { type: 'afterburner', cooldown: 4.8, duration: 3.8, energy: 34, thrustScale: 2.7, speedScale: 2.18 } },
        null_vector_afterburner: { id: 'null_vector_afterburner', name: 'Null Vector Afterburner', description: 'A raider surge tuned for violent speed spikes and rapid attack-angle resets.', slot: 'ability', mass: 8, cost: C(2260, 95, 168), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'], ability: { type: 'afterburner', cooldown: 4.4, duration: 2.7, energy: 32, thrustScale: 2.9, speedScale: 2.35 } },
        concord_sunburst_afterburner: { id: 'concord_sunburst_afterburner', name: 'Concord Sunburst Afterburner', description: 'A super-rare Concord pursuit drive with no cooldown; only reactor reserve and thermal load limit repeated ignition.', slot: 'ability', mass: 9, cost: C(3200, 80, 230), tier: 8, unlock: 'concordCapital', vendors: ['sunfall_citadel', 'marchlight_citadel'], ability: { type: 'afterburner', cooldown: 0, duration: 2.2, energy: 22, heat: 24, thrustScale: 2.82, speedScale: 2.28 } },
        blink_drive_ii: { id: 'blink_drive_ii', name: 'Blink Drive II', description: 'A refined translation snap with lower energy loss and a shorter recalibration window.', slot: 'ability', mass: 6, cost: C(840, 42, 22), tier: 3, unlock: 'rim', vendors: ['rim_observatory', 'aster_archive'], ability: { type: 'blink', cooldown: 6.8, distance: 410, energy: 20 } },
        blink_drive_iii: { id: 'blink_drive_iii', name: 'Blink Drive III', description: 'A late rift-step module tuned for frequent short hops under heavy combat pressure.', slot: 'ability', mass: 8, cost: C(1520, 95, 70), tier: 5, unlock: 'orchidLate', vendors: ['orchid_spindle', 'gemini_crown'], ability: { type: 'blink', cooldown: 5.4, distance: 470, energy: 17 } },
        orchid_blink_drive: { id: 'orchid_blink_drive', name: 'Orchid Blink Drive', description: 'A ritual microfold drive that trades some reach for much cheaper repeat translation.', slot: 'ability', mass: 8, cost: C(1640, 125, 58), tier: 5, unlock: 'orchidLate', vendors: ['orchid_spindle'], ability: { type: 'blink', cooldown: 4.8, distance: 420, energy: 14 } },
        horizon_blink_drive: { id: 'horizon_blink_drive', name: 'Horizon Blink Drive', description: 'A tier-seven fold drive with efficient long-hop translation and a short recalibration cycle.', slot: 'ability', mass: 9, cost: C(2440, 150, 125), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'], ability: { type: 'blink', cooldown: 4.6, distance: 540, energy: 13 } },
        orchid_nullstep_blink: { id: 'orchid_nullstep_blink', name: 'Orchid Nullstep Blink', description: 'A super-rare Orchid phase rite with no cooldown; every step is paid directly in energy and dangerous heat.', slot: 'ability', mass: 9, cost: C(3050, 240, 105), tier: 8, unlock: 'orchidLate', vendors: ['orchid_spindle'], ability: { type: 'blink', cooldown: 0, distance: 430, energy: 16, heat: 22 } },
        bastion_overcharger: { id: 'bastion_overcharger', name: 'Bastion Overcharger', description: 'A tier-six Concord overcharger that gives heavy shields a decisive holding window.', slot: 'ability', mass: 9, cost: C(1580, 28, 112), tier: 6, unlock: 'concordCapital', vendors: ['sunfall_citadel', 'marchlight_citadel'], ability: { type: 'overshield', cooldown: 13, duration: 8, amount: 135, energy: 42 } },
        gemini_interdictor_pulse: { id: 'gemini_interdictor_pulse', name: 'Gemini Interdictor Pulse', description: 'A tier-six command EMP that locks a wide lane before paired doctrine fire arrives.', slot: 'ability', mass: 8, cost: C(1500, 58, 108), tier: 6, unlock: 'geminiLate', vendors: ['gemini_crown'], ability: { type: 'emp', cooldown: 10.5, duration: 5.5, radius: 430, damage: 48, energy: 38 } },
        horizon_repair_cloud: { id: 'horizon_repair_cloud', name: 'Horizon Repair Cloud', description: 'A tier-seven autonomous repair cloud for long-route flagships that cannot limp home.', slot: 'ability', mass: 9, cost: C(2300, 130, 120), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'], ability: { type: 'repair', cooldown: 26, duration: 8, amount: 92, energy: 44 } },
        null_phase_cloak: { id: 'null_phase_cloak', name: 'Null Phase Cloak', description: 'A tier-seven raider cloak with a shorter reset window and cleaner firing break.', slot: 'ability', mass: 8, cost: C(2180, 120, 130), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'], ability: { type: 'cloak', cooldown: 15, duration: 7, energy: 34 } },
        aster_survey_matrix: { id: 'aster_survey_matrix', name: 'Aster Survey Matrix', description: 'A late utility lattice for distant signals, faster recovery links, and chart-heavy careers.', slot: 'utility', mass: 5, sensor: 760, interactionRange: 120, cost: C(1180, 82, 36), tier: 5, unlock: 'asterLate', vendors: ['aster_archive'] },
        auric_field_foundry: { id: 'auric_field_foundry', name: 'Auric Field Foundry', description: 'A heavy utility plant converting spare mass into repair output, cooling, and cargo slack.', slot: 'utility', mass: 9, repair: .9, cooling: 6, cargo: 10, cost: C(1500, 35, 95), tier: 6, unlock: 'auricLate', vendors: ['auric_exchange'] },
        gemini_targeting_grid: { id: 'gemini_targeting_grid', name: 'Gemini Targeting Grid', description: 'A tier-six doctrine utility that reduces weapon heat and extends sensor locks.', slot: 'utility', mass: 7, sensor: 520, cooling: 5, weaponHeat: -.1, cost: C(1580, 55, 104), tier: 6, unlock: 'geminiLate', vendors: ['gemini_crown'] },
        null_heat_exchanger: { id: 'null_heat_exchanger', name: 'Null Heat Exchanger', description: 'A tier-seven utility exchanger for captains pushing hot weapons past civilized limits.', slot: 'utility', mass: 8, cooling: 18, weaponHeat: -.14, repair: .25, cost: C(2050, 80, 145), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'] },
        horizon_vector_suite: { id: 'horizon_vector_suite', name: 'Horizon Vector Suite', description: 'Tier-seven support avionics for long-route captains who need reach, sensors, and thermal reserve.', slot: 'utility', mass: 8, sensor: 950, interactionRange: 190, cooling: 12, cost: C(2200, 145, 120), tier: 7, unlock: 'allGalaxies', vendors: ['waypoint_zero', 'terminus_exchange'] },
        deadplate_citadel: { id: 'deadplate_citadel', name: 'Deadplate Citadel', description: 'A shieldless tier-seven armor citadel for captains who expect to be hit and remain.', slot: 'defense', mass: 24, shield: 0, hullBonus: 180, armor: .38, shieldRecharge: 0, shieldDelay: 0, cost: C(2100, 25, 150), tier: 7, unlock: 'nullCrown', vendors: ['nullwake_hold', 'deadstar_anchorage'] }
    });
    ns.Data.normalizeModuleTravelFlags?.();
    Object.assign(ns.Data.WORLD_OBJECT_TYPES, {
        sealed_module_cache: { id: 'sealed_module_cache', name: 'Sealed Module Cache', backdrops: { belt: 1, core: 2, frontier: 3, null: 2, anomaly: 2 }, minDanger: 2, interactionDuration: 4, style: 'module-cache', color: '#55d7ff', reward: { aetherium: 20 }, rewardType: 'salvage', xp: 35, moduleLoot: { slots: ['utility', 'cargo', 'defense', 'primary'], minTier: 2, maxTier: 4 } },
        battlefield_hardware_crate: { id: 'battlefield_hardware_crate', name: 'Battlefield Hardware Crate', backdrops: { core: 2, null: 4, frontier: 2 }, minDanger: 3, interactionDuration: 4.5, style: 'module-cache', color: '#ff9b42', reward: { helionite: 2 }, rewardType: 'salvage', xp: 45, ambushChance: .3, moduleLoot: { slots: ['primary', 'defense', 'engine', 'reactor'], minTier: 3, maxTier: 6 } },
        prism_tech_cache: { id: 'prism_tech_cache', name: 'Prism Tech Cache', backdrops: { anomaly: 5 }, minDanger: 4, interactionDuration: 5, style: 'module-cache', color: '#ce75ff', reward: { sunshards: 6 }, rewardType: 'discovery', xp: 60, heat: 18, energyDrain: 12, moduleLoot: { slots: ['primary', 'defense', 'reactor', 'ability'], minTier: 4, maxTier: 6 } },
        ancient_armory_fragment: { id: 'ancient_armory_fragment', name: 'Ancient Armory Fragment', backdrops: { anomaly: 2, null: 1 }, minDanger: 5, interactionDuration: 6, style: 'armory-fragment', color: '#d8f7ff', reward: { sunshards: 10, helionite: 4 }, rewardType: 'discovery', xp: 90, moduleLoot: { slots: ['primary', 'cargo', 'defense'], minTier: 5, maxTier: 7 } }
    });
    ns.Data.MODULES.pulse_mk1.weapon = 'pulse'; ns.Data.MODULES.pulse_mk2.weapon = 'pulse'; ns.Data.MODULES.rail_driver.weapon = 'rail'; ns.Data.MODULES.seeker_rack.weapon = 'seeker';

    const ENEMY_TYPES = {
        bandit: { id: 'bandit', name: 'Bandit Cutter', faction: 'bandits', team: 'bandits', radius: 14, hull: 62, speed: 96, preferredRange: 250, weapon: 'pulse', damage: 12, cooldown: 1.35, shape: 'cutter', reward: 1 },
        interceptor: { id: 'interceptor', name: 'Interceptor', faction: 'bandits', team: 'bandits', radius: 12, hull: 42, speed: 145, preferredRange: 185, weapon: 'pulse', damage: 9, cooldown: .72, shape: 'dart', reward: .8 },
        gunship: { id: 'gunship', name: 'Gunship', faction: 'bandits', team: 'bandits', radius: 19, hull: 120, speed: 62, preferredRange: 430, weapon: 'rail', damage: 19, cooldown: 1.8, shape: 'block', reward: 1.5 },
        missile_skiff: { id: 'missile_skiff', name: 'Missile Skiff', faction: 'bandits', team: 'bandits', radius: 14, hull: 58, speed: 86, preferredRange: 520, weapon: 'seeker', damage: 11, cooldown: 2.2, shape: 'fork', reward: 1.25 },
        striker: { id: 'striker', name: 'Striker', faction: 'bandits', team: 'bandits', radius: 13, hull: 52, speed: 130, preferredRange: 120, weapon: 'scatter', damage: 7, cooldown: 1.1, shape: 'blade', reward: 1 },
        concord_patrol: { id: 'concord_patrol', name: 'Concord Patrol', faction: 'concord', team: 'concord', radius: 15, hull: 82, speed: 105, preferredRange: 330, weapon: 'pulse', damage: 13, cooldown: 1.05, shape: 'shield', reward: 1.2 },
        corsair_raider: { id: 'corsair_raider', name: 'Corsair Raider', faction: 'corsairs', team: 'corsairs', radius: 14, hull: 70, speed: 122, preferredRange: 230, weapon: 'scatter', damage: 8, cooldown: 1.15, shape: 'hook', reward: 1.2 },
        aster_scout: { id: 'aster_scout', name: 'Aster Survey Wing', faction: 'aster_collective', team: 'aster_collective', radius: 13, hull: 68, speed: 128, preferredRange: 390, weapon: 'ion', damage: 9, cooldown: 1.25, shape: 'dart', reward: 1.25 },
        orchid_cultivator: { id: 'orchid_cultivator', name: 'Orchid Cultivator', faction: 'orchid_synod', team: 'orchid_synod', radius: 17, hull: 102, speed: 82, preferredRange: 420, weapon: 'arc', damage: 14, cooldown: 1.45, shape: 'layer', reward: 1.4 },
        auric_enforcer: { id: 'auric_enforcer', name: 'Auric Enforcer', faction: 'auric_combine', team: 'auric_combine', radius: 18, hull: 112, speed: 76, preferredRange: 480, weapon: 'rail', damage: 18, cooldown: 1.7, shape: 'block', reward: 1.5 },
        cyan_skiff: { id: 'cyan_skiff', name: 'Cyan Fleet Skiff', faction: 'cyan_nomads', team: 'cyan_nomads', radius: 14, hull: 76, speed: 118, preferredRange: 270, weapon: 'flak', damage: 10, cooldown: 1.1, shape: 'fork', reward: 1.3 },
        gemini_spear: { id: 'gemini_spear', name: 'Gemini Spear', faction: 'gemini_directorate', team: 'gemini_directorate', radius: 16, hull: 96, speed: 112, preferredRange: 350, weapon: 'beam', damage: 17, cooldown: 1.55, shape: 'lancer', reward: 1.45 },
        torpedo_bomber: { id: 'torpedo_bomber', name: 'Torpedo Bomber', faction: 'bandits', team: 'bandits', radius: 18, hull: 105, speed: 58, preferredRange: 590, weapon: 'bloodhound', damage: 18, cooldown: 3.1, shape: 'bomber', reward: 1.7, minDanger: 3, role: 'artillery', telegraph: .9 },
        beam_lancer: { id: 'beam_lancer', name: 'Beam Lancer', faction: 'concord', team: 'concord', radius: 17, hull: 92, speed: 82, preferredRange: 520, weapon: 'beam', damage: 31, cooldown: 2.7, shape: 'lancer', reward: 1.6, minDanger: 3, role: 'artillery', telegraph: 1.1 },
        mine_layer: { id: 'mine_layer', name: 'Mine Layer', faction: 'corsairs', team: 'corsairs', radius: 16, hull: 86, speed: 92, preferredRange: 410, weapon: 'pulse', damage: 10, cooldown: 2.4, shape: 'layer', reward: 1.5, minDanger: 3, role: 'controller', ability: 'mines' },
        support_tender: { id: 'support_tender', name: 'Support Tender', faction: 'bandits', team: 'bandits', radius: 20, hull: 135, speed: 52, preferredRange: 460, weapon: 'pulse', damage: 7, cooldown: 2, shape: 'tender', reward: 1.8, minDanger: 4, role: 'support', ability: 'repair' },
        jammer_drone: { id: 'jammer_drone', name: 'Jammer Drone', faction: 'bandits', team: 'bandits', radius: 13, hull: 55, speed: 118, preferredRange: 300, weapon: 'ion', damage: 8, cooldown: 1.4, shape: 'jammer', reward: 1.4, minDanger: 4, role: 'support', ability: 'jammer' }
    };
    const BOSSES = {
        marauder_carrier: { id: 'marauder_carrier', name: 'Marauder Carrier', faction: 'bandits', team: 'bandits', radius: 58, hull: 1100, speed: 38, preferredRange: 480, weapon: 'scatter', damage: 13, cooldown: 1.3, shape: 'carrier', deploy: 'interceptor', reward: 10 },
        aegis_frigate: { id: 'aegis_frigate', name: 'Aegis Frigate', faction: 'concord', team: 'concord', radius: 52, hull: 980, speed: 44, preferredRange: 560, weapon: 'beam', damage: 34, cooldown: 2.8, shape: 'aegis', deploy: 'concord_patrol', reward: 10 },
        void_reaver: { id: 'void_reaver', name: 'Void Reaver', faction: 'corsairs', team: 'corsairs', radius: 49, hull: 900, speed: 72, preferredRange: 390, weapon: 'seeker', damage: 25, cooldown: 1.9, shape: 'reaver', deploy: 'corsair_raider', reward: 10, controller: 'reaver' },
        foundry_ark: { id: 'foundry_ark', name: 'Foundry Ark', faction: 'bandits', team: 'bandits', radius: 82, hull: 1750, speed: 25, preferredRange: 560, weapon: 'scatter', damage: 16, cooldown: 1.5, shape: 'foundry', deploy: 'torpedo_bomber', reward: 18, capital: true, controller: 'foundry', components: [{ id: 'bay_port', name: 'Port Fabricator', x: -42, y: 5, hull: 240, effect: 'deploy' }, { id: 'bay_starboard', name: 'Starboard Fabricator', x: 42, y: 5, hull: 240, effect: 'deploy' }] },
        solar_bastion: { id: 'solar_bastion', name: 'Solar Bastion', faction: 'concord', team: 'concord', radius: 76, hull: 1580, speed: 30, preferredRange: 620, weapon: 'beam', damage: 42, cooldown: 3.2, shape: 'solar', deploy: 'beam_lancer', reward: 18, capital: true, controller: 'bastion', components: [{ id: 'emitter_port', name: 'Port Emitter', x: -38, y: -4, hull: 210, effect: 'shield' }, { id: 'emitter_starboard', name: 'Starboard Emitter', x: 38, y: -4, hull: 210, effect: 'shield' }] },
        eclipse_cruiser: { id: 'eclipse_cruiser', name: 'Eclipse Cruiser', faction: 'corsairs', team: 'corsairs', radius: 70, hull: 1450, speed: 58, preferredRange: 440, weapon: 'bloodhound', damage: 34, cooldown: 2.4, shape: 'eclipse', deploy: 'jammer_drone', reward: 18, capital: true, controller: 'eclipse', components: [{ id: 'engine_port', name: 'Port Phase Engine', x: -30, y: 28, hull: 190, effect: 'blink' }, { id: 'engine_starboard', name: 'Starboard Phase Engine', x: 30, y: 28, hull: 190, effect: 'blink' }] }
    };

    const SPECIALIZATIONS = [
        ['ace_weapons_free','ace','Weapons Free','EXCLUSIVE POST-CAPSTONE // Alternating primary slots within 0.5 seconds empowers the second shot.','weaponsFree'],
        ['ace_target_hunter','ace','Target Hunter','EXCLUSIVE POST-CAPSTONE // Selected targets attract shots and suffer stronger critical hits.','targetHunter'],
        ['engineer_bulkheads','engineer','Emergency Bulkheads','EXCLUSIVE POST-CAPSTONE // Once per encounter, critical hull triggers resistance and repair.','bulkheads'],
        ['engineer_overclock','engineer','Unsafe Overclock','EXCLUSIVE POST-CAPSTONE // Abilities can be forced at half cooldown for heat and hull damage.','overclock'],
        ['pathfinder_ghost','pathfinder','Ghost Vector','EXCLUSIVE POST-CAPSTONE // Light Speed exit briefly masks the ship and boosts acceleration.','ghostVector'],
        ['pathfinder_field','pathfinder','Field Savant','EXCLUSIVE POST-CAPSTONE // Resolve searches farther away and complete interactions faster.','fieldSavant'],
        ['operator_marque','operator','Letter of Marque','EXCLUSIVE POST-CAPSTONE // Faction combat work grants stronger rewards and standing swings.','letterOfMarque'],
        ['operator_quartermaster','operator','Quartermaster','EXCLUSIVE POST-CAPSTONE // Deliveries and escorts earn a temporary destination service discount.','quartermaster']
    ].map(([id, discipline, name, description, flag]) => ({ id, discipline, name, description, effect: { [flag]: 1 }, maxRank: 1, capstone: false, specialization: true, display: { unit: 'capstone', label: 'SPECIALIZATION' } }));
    ns.Data.TRAITS.push(...SPECIALIZATIONS);

    const STATION_FLAIR = {
        independents: ['Dock crews trade repair gossip over open-band radio.', 'Guild traffic control promises no guarantees beyond a warm berth.'],
        concord: ['Beacon law is in force from approach vector to pressure seal.', 'Concord controllers log every drive flare and weapons discharge.'],
        corsairs: ['The berth fee buys discretion; survival remains your own expense.', 'Encrypted market calls crowd the local band with dangerous bargains.'],
        aster_collective: ['Survey crews exchange star maps before names.', 'Every arrival vector is archived for the common chart.'],
        orchid_synod: ['Violet condensers breathe along the spindle hull.', 'Docking hymns encode pressure and quarantine instructions.'],
        auric_combine: ['Your berth clock began before the clamps closed.', 'Every service has a price and every price has a witness.'],
        cyan_nomads: ['The freeport changes orbit more often than its crews change flags.', 'Salvage crews wave from hulls older than their family names.'],
        gemini_directorate: ['Two control voices issue one perfectly synchronized clearance.', 'Directorate sentries mirror every maneuver from opposite gantries.']
    };
    const STATION_DETAIL_BANK = {
        traffic: ['Inbound freighters are holding in a staggered burn lane.', 'Local patrols are asking pilots to keep weapons cold near the berth.', 'A maintenance tug keeps repainting scorch marks around bay three.'],
        rumor: ['Rumor tags mention salvage drifting beyond the safe beacon chain.', 'A broker is buying quiet stories about unusual module caches.', 'Pilots keep comparing strange static heard during Light Speed cooldown.'],
        market: ['Quartermasters are watching cargo space as closely as credit balances.', 'Module vendors are favoring practical fittings over showroom pieces.', 'The exchange board is quietly raising rates on rare hardware.'],
        shipyard: ['Frame crews have cleared a late-tier cradle for proven captains.', 'Shipwrights are logging hull stress before approving large-frame switches.', 'The yard foreman keeps a private list of pilots trusted with experimental mass budgets.'],
        policy: ['Station law treats optional briefings as advisory, but signed contracts as binding.', 'Dock control reminds captains that faction colors are not decoration here.', 'Every sealed cache belongs to whoever survives the recovery link.']
    };
    function stationDetails(station) {
        const pick = (kind, salt) => STATION_DETAIL_BANK[kind][Math.abs(ns.MathUtil.hash(station.x, station.y, salt) * STATION_DETAIL_BANK[kind].length) | 0];
        return { traffic: pick('traffic', 11), rumor: pick('rumor', 23), market: pick('market', 37), shipyard: pick('shipyard', 41), policy: pick('policy', 53) };
    }
    function hullAvailable(state, hull, station) {
        if (!hull || hull.id === 'wayfarer' || !station || (hull.majorOnly && !station.major)) return false;
        if (hull.vendors ? !hull.vendors.includes(station.id) : station.faction !== hull.faction) return false;
        if (hull.unlock === 'trade2') return ns.Unlocks.evaluate(state).tradeTier >= 2;
        if (hull.unlock === 'concord10') return state.reputations.concord >= 10;
        if (hull.unlock === 'corsairs10') return state.reputations.corsairs >= 10;
        if (hull.unlock === 'bulwark') return ns.Unlocks.evaluate(state).combat && state.reputations.concord >= 25;
        if (hull.unlock === 'ranger') return ns.Unlocks.evaluate(state).tradeTier >= 3 && state.visitedRegions.length >= 8;
        if (hull.unlock === 'concordElite') return ns.Unlocks.evaluate(state).combat && state.reputations.concord >= 25;
        if (hull.unlock === 'corsairElite') return state.stats.kills >= 30 && state.reputations.corsairs >= 25;
        if (hull.unlock === 'capitalVeteran') return state.pilot.level >= 10 && state.visitedRegions.includes('anomaly_rim') && Object.keys(state.progression?.bossesDefeated || {}).length > 0;
        if (hull.unlock === 'asterLate') return state.visitedGalaxies.includes('galaxy_c') && state.reputations.aster_collective >= 20;
        if (hull.unlock === 'orchidLate') return state.visitedGalaxies.includes('galaxy_d') && state.reputations.orchid_synod >= 20;
        if (hull.unlock === 'auricLate') return state.visitedGalaxies.includes('galaxy_e') && state.reputations.auric_combine >= 20;
        if (hull.unlock === 'cyanLate') return state.visitedGalaxies.includes('galaxy_f') && state.reputations.cyan_nomads >= 20;
        if (hull.unlock === 'geminiLate') return state.visitedGalaxies.includes('galaxy_g') && state.reputations.gemini_directorate >= 20;
        if (hull.unlock === 'concordCapital') return state.reputations.concord >= 40 && Object.keys(state.progression?.bossesDefeated || {}).some(id => ns.Data.BOSSES[id]?.capital);
        if (hull.unlock === 'allGalaxies') return state.pilot.level >= 14 && state.visitedGalaxies.length >= 7 && Object.keys(state.progression?.bossesDefeated || {}).some(id => ns.Data.BOSSES[id]?.capital);
        if (hull.unlock === 'nullCrown') return state.stats.kills >= 80 && state.reputations.corsairs >= 45 && Object.keys(state.progression?.bossesDefeated || {}).some(id => ns.Data.BOSSES[id]?.capital);
        return false;
    }
    function hullUnlockText(state, hull) {
        if (hullAvailable(state, hull, ns.Data.LANDMARKS.find(station => hull.vendors?.includes(station.id) || (station.major && station.faction === hull.faction)))) return 'AVAILABLE AT AUTHORIZED SHIPYARD';
        return { ranger: 'REQUIRES TRADE III + 8 REGIONS', concordElite: 'REQUIRES COMBAT LICENSE + 25 CONCORD', corsairElite: 'REQUIRES 30 KILLS + 25 CORSAIRS', capitalVeteran: 'REQUIRES LEVEL 10 + ANOMALY RIM + CAPITAL KILL', asterLate: 'REQUIRES ASTER GALAXY +20 STANDING', orchidLate: 'REQUIRES ORCHID GALAXY +20 STANDING', auricLate: 'REQUIRES AURIC GALAXY +20 STANDING', cyanLate: 'REQUIRES CYAN GALAXY +20 STANDING', geminiLate: 'REQUIRES GEMINI GALAXY +20 STANDING', concordCapital: 'REQUIRES +40 CONCORD + CAPITAL KILL', allGalaxies: 'REQUIRES LEVEL 14 + 7 GALAXIES + CAPITAL KILL', nullCrown: 'REQUIRES 80 KILLS +45 CORSAIRS + CAPITAL KILL' }[hull.unlock] || 'SHIPYARD LICENSE LOCKED';
    }
    function patrolStatus(state, faction) {
        if (state.pilot.allegiance === faction) return 'FRIENDLY';
        if (state.pilot.allegiance && (ns.Data.FACTIONS[state.pilot.allegiance]?.hostileTo || []).includes(faction)) return 'HOSTILE';
        const rep = state.reputations[faction] || 0; return rep >= 10 ? 'FRIENDLY' : rep >= 0 ? 'NEUTRAL' : 'HOSTILE';
    }
    function rivals(a, b) { return Boolean(a && b && (ns.Data.FACTIONS[a]?.hostileTo || []).includes(b)); }
    function dockingDenied(state, faction) { return (state.reputations[faction] || 0) <= -50; }
    function briefing(contract, station) {
        const faction = ns.Data.FACTIONS[contract.issuer] || ns.Data.FACTIONS.independents, destination = ns.Contracts?.destinationName(contract) || 'the marked contact';
        const code = String(Math.abs(ns.MathUtil.hash(contract.id.length, station.x, station.y, contract.risk) * 999) | 0).padStart(3, '0');
        const complication = contract.timer ? (contract.timer.hard ? 'Hard deadline clauses void payment after the clock expires.' : 'Timed bonus clauses favor a clean launch and direct route.') : contract.risk >= 5 ? 'Capital signatures may be masked until the final approach.' : contract.type === 'choice' ? 'Recipient choice will alter who claims the result.' : 'No unusual clauses beyond standard frontier liability.';
        return {
            contact: `${faction.short}-${code}`,
            situation: `${faction.name} traffic has flagged ${destination} for immediate attention.`,
            line: STATION_FLAIR[contract.issuer]?.[contract.risk % 2] || STATION_FLAIR.independents[0],
            route: `Origin ${station.name} // destination ${destination}`,
            complication,
            tone: contract.priority ? 'Patron tone: priority channel, public gratitude expected.' : `Patron tone: ${faction.short} discretion preferred.`,
            finePrint: contract.risk >= 4 ? 'Fine print: hostile interference is considered probable, not exceptional.' : 'Fine print: routine hazards remain the pilot responsibility.'
        };
    }
    ns.Data.HULLS = HULLS; ns.Data.WEAPON_TYPES = WEAPON_TYPES; ns.Data.ENEMY_TYPES = ENEMY_TYPES; ns.Data.BOSSES = BOSSES; ns.Data.STATION_FLAIR = STATION_FLAIR;
    ns.Expansion = { hullAvailable, hullUnlockText, patrolStatus, rivals, dockingDenied, stationDetails, briefing };
})(window.FrontierWayfarer);
